### ISSUE TITLE
0 value now returns 'None'

### ISSUE THREAD

**Issue by lekzz** [13hakta/zbxwmi#8]
After my distro removed python 1 and 2 i found you had already updated your script to python3. However after switching over, and updating everything to use -cred, it now returns 'None' where it used to return '0'.

This generates zabbix errors like:
`"item "SERVER:zbxwmi["-action","get","-item","3","-fields","PercentProcessorTime","Win32_PerfFormattedData_PerfOS_Processor","-cred","{$WMI_AUTHFILE}",{HOST.HOST}]" became not supported: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "None"`

```
$ sudo /etc/zabbix/externalscripts/zbxwmi -action get -item _Total -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -cred /etc/zabbix/wmi.pw SERVER

None
```

When it is able to read a real value it will become supported again and thus is constantly flip flopping.

If i change the type to text it won't flip flop but then graphs won't work. 
On hosts with history using latest data with values there are no more 0's to be found in the history since the switch to the python3 script, while they do show before.
I tried setting the interval to 5m but that didn't change anything, but in history i can see 1m never was a problem before.

Nothing has changed on the windows machines.

**Comment by 13hakta** [comment]
Resolved in latest update 0.1.3 with adding type hinting.
Option type must be added kind of `-type n`

**Comment by lekzz** [comment]
I updated to the new script and the -type setting, however the result is still the same.

`375424:20201201:155006.495 item "SERVER:zbxwmi["-action","get","-item","13","-fields","PercentProcessorTime","Win32_PerfFormattedData_PerfOS_Processor","-type","n","-cred","{$WMI_AUTHFILE}",{HOST.HOST}]" became not supported: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "None"
`

```
$ sudo /etc/zabbix/externalscripts/zbxwmi -action get -item _Total -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -type n -cred /etc/zabbix/wmi.pw SERVER
2

$ sudo /etc/zabbix/externalscripts/zbxwmi -action get -item _Total -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -type n -cred /etc/zabbix/wmi.pw SERVER
None
```

**Comment by lekzz** [comment]
Finally got around to doing some more testing and found that the problem is only with the "get" action, but it's working correctly with the "json" and "both "actions:

```
sudo /etc/zabbix/externalscripts/zbxwmi -action get -item "6" -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -t n -cred /etc/zabbix/wmi.pw SERVER
None

sudo /etc/zabbix/externalscripts/zbxwmi -action json -item "6" -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -t n -cred /etc/zabbix/wmi.pw SERVER
[{"Name": "6", "PercentProcessorTime": 0}]

sudo /etc/zabbix/externalscripts/zbxwmi -action both -item "6" -fields PercentProcessorTime Win32_PerfFormattedData_PerfOS_Processor -t n -cred /etc/zabbix/wmi.pw SERVER
{ "data": [ {"{#WMI.PERCENTPROCESSORTIME}": 0} ] }
```

So i ended up using json with the JSONPath preprocessor. However that preprocessor doesn't work with the [] brackets so i had to trim those first. Might be a seperate bug but unsure as this is the first time i worked with json data in zabbix.
